### ISSUE TITLE
final vcf file

### ISSUE THREAD

**Issue by hxtjc** [kehrlab/PopIns2#31]
Hello!
I need to see the length of these insertions, but I'm not sure which one is in the vcf file. Can you tell me how can I find the length of insertion from the final vcf file?
CM008168.2 146298 CM008168.2:146298:FP T ]SAMN05216016.NODE_12366_length_48_cov_3.875000f:61]T . . AR=39;AS=0.65;GS=1 GT:PL 0/1:255,0,255
CM008168.2 167091 CM008168.2:167091:FP G G[COMPONENT_102391_a_length_100_size_10f:76[ . . AR=10;AS=0.357143;GS=4 GT:PL 0/0:0,255,255

**Comment by Krannich479** [comment]
Hello hxtjc,
thank you for using PopIns2!

From your question I assume that you are interested in determining the precise base pair length of a non-reference sequence (NRS).

In the final VCF, PopIns2 reports the precise breakends in a supercontig (assuming both ends of the supercontig were successfully placed), i.e. where the NRS starts and ends with respect to the supercontig. As a reminder, _supercontigs_ consist of NRS plus some flanking sequence of the reference.
For a given supercontig that was successfully placed at both ends you can typically use two consecutive lines of the final VCF in order to determine the precise NRS and its length. Here is an example:

```
chr21	14869539	chr21:14869539:FP	A	A[contig_239f:90[	.	.	AR=3;AS=1;GS=1
chr21	14869538	chr21:14869538:FP	C	]contig_239f:402]C	.	.	AR=7;AS=1;GS=1
```

are two lines that contain the breakends of the supercontig "contig_239". The ALT field contains the alternative base or replacement string as specified in [VCF v4.2, chapter 5.4.1](https://samtools.github.io/hts-specs/VCFv4.2.pdf). In the example the NRS goes from position 90 to 402 in the supercontig, i.e. the NRS is 402-90+1 = 313 bp long.

Looking at your two given lines, it seems like they are not from the same supercontig since 1) the supercontig identifier is different and 2) the insertion breakpoints on the reference ("CM008168.2") are almost 800 bp apart.

I hope this helps. Please also see issue https://github.com/bkehr/popins/issues/3, as similar details were discussed there.

**Comment by hxtjc** [comment]
Oh! Thank you for your detailed explanation! 
But I'm sorry that I'm using PopIns. In future research, I am preparing to use PopIns2. The result of PopIns is not the same as that of PopIns2. I read your explanation of the problem in PopIns , but there is no clearly method for finding the length information of the inserted sequences. Can you tell me please? The result I get is something like this:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SRR934437
CM008168.2      27636   CM008168.2:27636:FP     T       ]COMPONENT_15835_g_length_394_size_50f:215]T    .       .       AR=54;AS=0.372414;GS=130        GT:PL   0/0:0,255,255
CM008168.2      27385   CM008168.2:27385:FP     A       ]SAMN05216022.NODE_8742_length_47_cov_3.212766r:11]A    .       .       AR=73;AS=0.752577;GS=7  GT:PL   0/0:0,255,255
CM008168.2      28111   CM008168.2:28111:FP     C       ]SAMN09379701.NODE_44842_length_100_cov_2.000000f:60]C  .       .       AR=5;AS=0.454545;GS=1   GT:PL   0/0:0,255,255
CM008168.2      28121   CM008168.2:28121:FP     C       ]SAMN05216027.NODE_9541_length_83_cov_2.048193r:74]C    .       .       AR=18;AS=0.352941;GS=3  GT:PL   0/0:0,255,255
CM008168.2      28324   CM008168.2:28324:FP     T       ]SAMN05216021.NODE_20080_length_68_cov_2.485294r:68]T   .       .       AR=16;AS=0.615385;GS=1  GT:PL   0/0:0,255,255
CM008168.2      28478   CM008168.2:28478:FP     A       A[COMPONENT_15835_g_length_394_size_50f:324[    .       .       AR=102;AS=0.447368;GS=244       GT:PL   0/0:0,118,255
CM008168.2      29980   CM008168.2:29980:FP     C       C[SAMN09379821.NODE_37434_length_136_cov_2.676471f:79[  .       .       AR=10;AS=0.384615;GS=9  GT:PL   0/0:0,255,255
CM008168.2      28662   CM008168.2:28662:FP     C       C[SAMN09379748.NODE_65046_length_50_cov_2.040000r:79[   .       .       AR=117;AS=0.92126;GS=5  GT:PL   0/0:0,236,255

**Comment by Krannich479** [comment]
To **calculate the length of a NRS** please see my previous answer. It is all about finding two breakends of the same supercontig in the VCF file. The records you posted here only have one common supercontig identifier (COMPONENT_15835), i.e. given only the records above you can compute only one precise NRS length. The other supercontigs might have only one successfully placed end or their second breakend appears not directly after the first within the VCF file (there are valid reasons for that). For instance, your COMPONENT_15835 has its breakends at position 215 and 394. Therefore, the NRS is of size 394-215+1=180 (bp).

Also, I **realized two more things given your data**:

1. The insertion positions on the reference genome "CM008168.2" for the breakends of COMPONENT_15835 are 842 bp apart. That means, assuming that the placing is correct, the allele carrying the NRS is actually smaller than the corresponding reference allele. Than can be biology, that can be an error of the placing. I recommend having a look at the sequence around the insertion positions in the reference.
2. The VCF records you shared above contain genotypes for only one individual (SRR934437) with most of them being homozygous non-carrier (0/0). That means these NRS are actually not present in that particular individual. 

Last but not least: it is absolutely possible to have **different NRS callsets with PopIns and PopIns2**. The rework done for the second major release can affect the NRS sequence itself as well as their flanking reference sequence. The differences between PopIns and PopIns2, particularly the new merge module, is described in [this](https://academic.oup.com/bioinformatics/article/38/3/604/6415820) publication.

**Comment by hxtjc** [comment]
Oh! I got it now! Thank you for your detailed explanation again! But I found that the length of the contig that is prefixed with a sample ID is not equal to the length in the contig name. For example:
CM008168.2      42600204        CM008168.2:42600204:FP  A       A[SAMN05216053.NODE_68028_length_98_cov_2.153061f:73[   .       .       AR=26;AS=0.604651;GS=1  GT:PL   0/0:0,20,255
CM008168.2      42600443        CM008168.2:42600443:FP  T       ]SAMN05216053.NODE_68028_length_98_cov_2.153061f:75]T   .       .       AR=42;AS=0.567568;GS=1  GT:PL   0/0:0,12,165
This is the sequence of SAMN05216053.NODE_68028_length_98_cov_2.153061:
>SAMN05216053.NODE_68028_length_98_cov_2.153061
CCCCAAAATAAGAAAATATATAACTCCATTAAAAATGGACAAAAGGTTTAAACAGACACTTTAGTAAGCTAGACATGCTGCCAAGTCACTTCAGTCGGGTCCGACTCTGTGCGACCCCATGGACTGCCGCCTACCAGGCTCCTC
Its true length is 144 bp. Why is this？
And what does "cov_2.153061" mean in SAMN05216053.NODE_68028_length_98_cov_2.153061?

**Comment by Krannich479** [comment]
hi hxtjc,
in PopIns (not PopIns2!) part of the supercontig's identifier originates from the external assembler, which is Velvet by default. The length is given in number of k-mers. Since PopIns uses Velvet with k=47 by default your example makes perfect sense: the supercontig is 144 bp long but 98 k-mers long. 144-(47-1)=98, the length of your supercontig.

The "cov_2" is another information from the assembler. It means that each k-mer of the assembled contigs has a minimum abundance of 2 in the input data. This is a common setup in de Bruijn Graph based assemblers to overcome base errors in the input data.

To be honest, I don't know what the "153061" is about. Does that number appear already in the assembled contigs (after the assemble module) or only in the supercontigs (after the merging module)?

**Comment by bkehr** [comment]
The coverage is 2.153061 and not 2.

**Comment by Krannich479** [comment]
Oh, I misinterpreted that. Thanks @bkehr, I updated my last reply.

**Comment by hxtjc** [comment]
Thank you very much for your answers, and now I understand！
