### ISSUE TITLE
popins2 merge can not do properly

### ISSUE THREAD

**Issue by ld9866** [kehrlab/PopIns2#33]
Hello software developers!
We are using popins2 software for data processing, the assemble step is done very well, but when we use "popins2 merge" we find that it cannot be used normally, I have attached my code and error message, please take a look at the what is the problem
good day!

popins2 merge -r /home/xxx/Data/PRJEB27654/ -di
=========================================================
popins2 version    : 0.13.0-47964d4
PARAMETER ======== : VALUE ==============================
verbose            : 0
threads            : 1
#filename_seq_in   : 0
#filename_ref_in   : 13
filename_graph_in  : 
filename_colors_in : 
k                  : 63
g                  : 49
clip-tips          : 1
delete-isolated    : 1
mercy-kmers        : 0
outputfile-prefix  : supercontigs
setcover-min-kmers : 62
min-entropy        : 0
write-setcover     : 0
write-lecc         : 0
=========================================================
[popins2 2022-09-05 17:26:06] Building CCDBG
*** stack smashing detected ***: terminated
已放弃 (核心已转储)

**Comment by Krannich479** [comment]
Hello,
thanks for using PopIns2! What you are reporting is a C language error. It seems something goes wrong during the construction of the colored de Bruijn Graph.

For consistency, can you please verify that you:
1. Use a recommended setup and versions (OS, compiler and Bifrost). In particular, Bifrost underwent a lot of changes since my last compatibility tests. Please verify that a recommended version is used.
2. Do not run into trouble with CPU instruction sets on a heterogeneous compute cluster. (Please see Q3 of PopIns2's [FAQ](https://github.com/kehrlab/PopIns2/wiki/Troubleshooting---FAQ) for more info.)
3. Can use Bifrost itself without PopIns2. I.e. please verify that you can build a simple colored and compacted de Bruijn Graph using the [Bifrost CLI](https://github.com/pmelsted/bifrost#binary-usage).

Thanks.

**Comment by ld9866** [comment]
Thank you very much for your reply!
I've tested it since I got your reply, and the Bifrost version I'm currently using is exactly what you recommended, but the problem persists and hasn't been resolved.
I don't quite understand what you said about "Can use Bifrost itself without PopIns2", how can I implement this step of popins2 merge, so that I can continue to use the next module?
The last small suggestion, can you think about the environment configuration of conda or the deployment method of docker, I have been troubled by this problem for a long time.
good luck!

**Comment by Krannich479** [comment]
Hi,
one more error I'd like to exclude is the memory settings of Bifrost: can you verify that the _CMakeList.txt_ within your Bifrost installation has the MAX_KMER_SIZE set to 64? If it is at 32 (default) this causes the memory fault of your PopIns2 run. This error would also not be covered by your 'Bifrost build' test yet.

**Comment by ld9866** [comment]
Hello, 
Your new suggestion solved the problem perfectly, and it is now running on our server, thank you for your patience!
good luck!
